Accept ranges + optimize splitting

diff --git a/tmux/layout b/tmux/layout
--- a/tmux/layout
+++ b/tmux/layout
@@ -4,7 +4,7 @@ if [[ $1 == -@(h|-h)* ]]
 then
 cat << 'HELP'
 Usage:
-layout {host prefix} [number of hosts (>1, default: 3)] OR
+layout {host prefix} [range or number of hosts (default: 1-3)] OR
        host1 host2 ...
 HELP
 exit 0
@@ -12,22 +12,32 @@ fi
 
 nb_sessions="$(tmux ls -F#S 2>/dev/null | wc -l)"
 
-if ((nb_sessions == 0))
-then
-   tmux new -s tiles -d
-fi
-
-if (($# <= 1)) || { (($# == 2)) && [[ $2 == [0-9]* ]]; }
+if (($# <= 1)) || { (($# == 2)) && [[ $2 == [0-9]* || $2 == [0-9]*-[0-9]* ]]; }
 then
    if (($# == 0))
    then
       read -p 'Common host prefix: ' prefix
-      read -p 'Number of hosts: ' nb_hosts
+      read -p 'Range or number of hosts (ex: [1-]3): ' range
    else
       prefix="$1"
-      nb_hosts="${2:-3}"
+      range="${2:-1-3}"
    fi
-   [[ $2 == [01] ]] && { echo "Abort. The second arg must be > 1" 1>&2; exit 1; }
+
+   [[ $2 == [01] ]] && { echo 'Abort. Number > 1 expected' 1>&2; exit 1; }
+
+   [[ $range != *-* ]] && range=1-"$range"
+
+   range_start="${range%-*}"
+   range_end="${range#*-}"
+
+   nb_hosts="$((range_end - range_start + 1))"
+
+   if ((nb_hosts < 2))
+   then
+      echo 'Invalid range. Number of hosts must be > 1' 1>&2; exit 2
+   fi
+
+   ((nb_sessions == 0)) && tmux new -s tiles -d
 
    tmux new-window -n "$prefix" "ssh ${prefix}1"
 
@@ -38,6 +48,8 @@ then
       tmux select-layout tiled >/dev/null
    done
 else
+   ((nb_sessions == 0)) && tmux new -s tiles -d
+
    tmux new-window -n 'multi' "ssh $1"
 
    j=2
@@ -49,7 +61,7 @@ else
    done
 fi
 
-if { [[ $nb_hosts ]] && ((nb_hosts < 4)); } || { [[ ! $nb_hosts ]] && (($# < 4)); }
+if { [[ $nb_hosts ]] && ((nb_hosts == 3)); } || { [[ ! $nb_hosts ]] && (($# == 3)); }
 then
    tmux select-layout even-horizontal >/dev/null
 fi
